### ISSUE TITLE
List of bitdevs meetups

### ISSUE THREAD

**Issue by ldecferreira** [BitDevsNYC/BitDevsNYC.github.io#73]
How do you feel about adding an area in the website with a list of all Bitdevs meetups around the world?

https://austinbitdevs.com/
https://www.sfbitcoindevs.org/
https://bitdevsla.org/
http://bitdevsportugues.org/
https://bitdevsespanol.org/
https://www.meetup.com/pt-BR/Bitcoin_Sydney/
https://www.meetup.com/pt-BR/BitDevsLDN/

**Comment by jnewbery** [comment]
See also #35

**Comment by ldecferreira** [comment]
@jnewbery Why is it a bad idea?

**Comment by jnewbery** [comment]
The problem is that curating such a list becomes inherently political. Someone needs to decide what should be included and what excluded, and some people are going to get upset whatever happens.

We therefore decided to keep this website exclusively focused on the NY BitDevs meetups. Other meetups are very welcome to use the material in whatever way is useful to them.

**Comment by ldecferreira** [comment]
I understand, thank you!
